/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.ArtifactResultNodeStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ArtifactGCStatus describes the result of the deletion
 */
@ApiModel(description = "ArtifactGCStatus describes the result of the deletion")

public class ArtifactGCStatus {
  public static final String SERIALIZED_NAME_ARTIFACT_RESULTS_BY_NODE = "artifactResultsByNode";
  @SerializedName(SERIALIZED_NAME_ARTIFACT_RESULTS_BY_NODE)
  private Map<String, ArtifactResultNodeStatus> artifactResultsByNode = null;


  public ArtifactGCStatus artifactResultsByNode(Map<String, ArtifactResultNodeStatus> artifactResultsByNode) {
    
    this.artifactResultsByNode = artifactResultsByNode;
    return this;
  }

  public ArtifactGCStatus putArtifactResultsByNodeItem(String key, ArtifactResultNodeStatus artifactResultsByNodeItem) {
    if (this.artifactResultsByNode == null) {
      this.artifactResultsByNode = new HashMap<String, ArtifactResultNodeStatus>();
    }
    this.artifactResultsByNode.put(key, artifactResultsByNodeItem);
    return this;
  }

   /**
   * ArtifactResultsByNode maps Node name to result
   * @return artifactResultsByNode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ArtifactResultsByNode maps Node name to result")

  public Map<String, ArtifactResultNodeStatus> getArtifactResultsByNode() {
    return artifactResultsByNode;
  }


  public void setArtifactResultsByNode(Map<String, ArtifactResultNodeStatus> artifactResultsByNode) {
    this.artifactResultsByNode = artifactResultsByNode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArtifactGCStatus artifactGCStatus = (ArtifactGCStatus) o;
    return Objects.equals(this.artifactResultsByNode, artifactGCStatus.artifactResultsByNode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(artifactResultsByNode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArtifactGCStatus {\n");
    sb.append("    artifactResultsByNode: ").append(toIndentedString(artifactResultsByNode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

