/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ArtifactoryArtifactRepository defines the controller configuration for an artifactory artifact repository
 */
@ApiModel(description = "ArtifactoryArtifactRepository defines the controller configuration for an artifactory artifact repository")

public class ArtifactoryArtifactRepository {
  public static final String SERIALIZED_NAME_KEY_FORMAT = "keyFormat";
  @SerializedName(SERIALIZED_NAME_KEY_FORMAT)
  private String keyFormat;

  public static final String SERIALIZED_NAME_PASSWORD_SECRET = "passwordSecret";
  @SerializedName(SERIALIZED_NAME_PASSWORD_SECRET)
  private io.kubernetes.client.openapi.models.V1SecretKeySelector passwordSecret;

  public static final String SERIALIZED_NAME_REPO_U_R_L = "repoURL";
  @SerializedName(SERIALIZED_NAME_REPO_U_R_L)
  private String repoURL;

  public static final String SERIALIZED_NAME_USERNAME_SECRET = "usernameSecret";
  @SerializedName(SERIALIZED_NAME_USERNAME_SECRET)
  private io.kubernetes.client.openapi.models.V1SecretKeySelector usernameSecret;


  public ArtifactoryArtifactRepository keyFormat(String keyFormat) {
    
    this.keyFormat = keyFormat;
    return this;
  }

   /**
   * KeyFormat defines the format of how to store keys and can reference workflow variables.
   * @return keyFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "KeyFormat defines the format of how to store keys and can reference workflow variables.")

  public String getKeyFormat() {
    return keyFormat;
  }


  public void setKeyFormat(String keyFormat) {
    this.keyFormat = keyFormat;
  }


  public ArtifactoryArtifactRepository passwordSecret(io.kubernetes.client.openapi.models.V1SecretKeySelector passwordSecret) {
    
    this.passwordSecret = passwordSecret;
    return this;
  }

   /**
   * Get passwordSecret
   * @return passwordSecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public io.kubernetes.client.openapi.models.V1SecretKeySelector getPasswordSecret() {
    return passwordSecret;
  }


  public void setPasswordSecret(io.kubernetes.client.openapi.models.V1SecretKeySelector passwordSecret) {
    this.passwordSecret = passwordSecret;
  }


  public ArtifactoryArtifactRepository repoURL(String repoURL) {
    
    this.repoURL = repoURL;
    return this;
  }

   /**
   * RepoURL is the url for artifactory repo.
   * @return repoURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "RepoURL is the url for artifactory repo.")

  public String getRepoURL() {
    return repoURL;
  }


  public void setRepoURL(String repoURL) {
    this.repoURL = repoURL;
  }


  public ArtifactoryArtifactRepository usernameSecret(io.kubernetes.client.openapi.models.V1SecretKeySelector usernameSecret) {
    
    this.usernameSecret = usernameSecret;
    return this;
  }

   /**
   * Get usernameSecret
   * @return usernameSecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public io.kubernetes.client.openapi.models.V1SecretKeySelector getUsernameSecret() {
    return usernameSecret;
  }


  public void setUsernameSecret(io.kubernetes.client.openapi.models.V1SecretKeySelector usernameSecret) {
    this.usernameSecret = usernameSecret;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArtifactoryArtifactRepository artifactoryArtifactRepository = (ArtifactoryArtifactRepository) o;
    return Objects.equals(this.keyFormat, artifactoryArtifactRepository.keyFormat) &&
        Objects.equals(this.passwordSecret, artifactoryArtifactRepository.passwordSecret) &&
        Objects.equals(this.repoURL, artifactoryArtifactRepository.repoURL) &&
        Objects.equals(this.usernameSecret, artifactoryArtifactRepository.usernameSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyFormat, passwordSecret, repoURL, usernameSecret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArtifactoryArtifactRepository {\n");
    sb.append("    keyFormat: ").append(toIndentedString(keyFormat)).append("\n");
    sb.append("    passwordSecret: ").append(toIndentedString(passwordSecret)).append("\n");
    sb.append("    repoURL: ").append(toIndentedString(repoURL)).append("\n");
    sb.append("    usernameSecret: ").append(toIndentedString(usernameSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

