/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Column is a custom column that will be exposed in the Workflow List View.
 */
@ApiModel(description = "Column is a custom column that will be exposed in the Workflow List View.")

public class Column {
  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public Column key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * The key of the label or annotation, e.g., \&quot;workflows.argoproj.io/completed\&quot;.
   * @return key
  **/
  @ApiModelProperty(required = true, value = "The key of the label or annotation, e.g., \"workflows.argoproj.io/completed\".")

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public Column name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of this column, e.g., \&quot;Workflow Completed\&quot;.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The name of this column, e.g., \"Workflow Completed\".")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Column type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of this column, \&quot;label\&quot; or \&quot;annotation\&quot;.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The type of this column, \"label\" or \"annotation\".")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Column column = (Column) o;
    return Objects.equals(this.key, column.key) &&
        Objects.equals(this.name, column.name) &&
        Objects.equals(this.type, column.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, name, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Column {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

