/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.BasicAuth;
import io.argoproj.workflow.models.ClientCertAuth;
import io.argoproj.workflow.models.OAuth2Auth;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * HTTPAuth
 */

public class HTTPAuth {
  public static final String SERIALIZED_NAME_BASIC_AUTH = "basicAuth";
  @SerializedName(SERIALIZED_NAME_BASIC_AUTH)
  private BasicAuth basicAuth;

  public static final String SERIALIZED_NAME_CLIENT_CERT = "clientCert";
  @SerializedName(SERIALIZED_NAME_CLIENT_CERT)
  private ClientCertAuth clientCert;

  public static final String SERIALIZED_NAME_OAUTH2 = "oauth2";
  @SerializedName(SERIALIZED_NAME_OAUTH2)
  private OAuth2Auth oauth2;


  public HTTPAuth basicAuth(BasicAuth basicAuth) {
    
    this.basicAuth = basicAuth;
    return this;
  }

   /**
   * Get basicAuth
   * @return basicAuth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BasicAuth getBasicAuth() {
    return basicAuth;
  }


  public void setBasicAuth(BasicAuth basicAuth) {
    this.basicAuth = basicAuth;
  }


  public HTTPAuth clientCert(ClientCertAuth clientCert) {
    
    this.clientCert = clientCert;
    return this;
  }

   /**
   * Get clientCert
   * @return clientCert
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ClientCertAuth getClientCert() {
    return clientCert;
  }


  public void setClientCert(ClientCertAuth clientCert) {
    this.clientCert = clientCert;
  }


  public HTTPAuth oauth2(OAuth2Auth oauth2) {
    
    this.oauth2 = oauth2;
    return this;
  }

   /**
   * Get oauth2
   * @return oauth2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OAuth2Auth getOauth2() {
    return oauth2;
  }


  public void setOauth2(OAuth2Auth oauth2) {
    this.oauth2 = oauth2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HTTPAuth htTPAuth = (HTTPAuth) o;
    return Objects.equals(this.basicAuth, htTPAuth.basicAuth) &&
        Objects.equals(this.clientCert, htTPAuth.clientCert) &&
        Objects.equals(this.oauth2, htTPAuth.oauth2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(basicAuth, clientCert, oauth2);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HTTPAuth {\n");
    sb.append("    basicAuth: ").append(toIndentedString(basicAuth)).append("\n");
    sb.append("    clientCert: ").append(toIndentedString(clientCert)).append("\n");
    sb.append("    oauth2: ").append(toIndentedString(oauth2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

