/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.Column;
import io.argoproj.workflow.models.Link;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * InfoResponse
 */

public class InfoResponse {
  public static final String SERIALIZED_NAME_COLUMNS = "columns";
  @SerializedName(SERIALIZED_NAME_COLUMNS)
  private List<Column> columns = null;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private List<Link> links = null;

  public static final String SERIALIZED_NAME_MANAGED_NAMESPACE = "managedNamespace";
  @SerializedName(SERIALIZED_NAME_MANAGED_NAMESPACE)
  private String managedNamespace;

  public static final String SERIALIZED_NAME_MODALS = "modals";
  @SerializedName(SERIALIZED_NAME_MODALS)
  private Map<String, Boolean> modals = null;

  public static final String SERIALIZED_NAME_NAV_COLOR = "navColor";
  @SerializedName(SERIALIZED_NAME_NAV_COLOR)
  private String navColor;


  public InfoResponse columns(List<Column> columns) {
    
    this.columns = columns;
    return this;
  }

  public InfoResponse addColumnsItem(Column columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<Column>();
    }
    this.columns.add(columnsItem);
    return this;
  }

   /**
   * Get columns
   * @return columns
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Column> getColumns() {
    return columns;
  }


  public void setColumns(List<Column> columns) {
    this.columns = columns;
  }


  public InfoResponse links(List<Link> links) {
    
    this.links = links;
    return this;
  }

  public InfoResponse addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Link> getLinks() {
    return links;
  }


  public void setLinks(List<Link> links) {
    this.links = links;
  }


  public InfoResponse managedNamespace(String managedNamespace) {
    
    this.managedNamespace = managedNamespace;
    return this;
  }

   /**
   * Get managedNamespace
   * @return managedNamespace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getManagedNamespace() {
    return managedNamespace;
  }


  public void setManagedNamespace(String managedNamespace) {
    this.managedNamespace = managedNamespace;
  }


  public InfoResponse modals(Map<String, Boolean> modals) {
    
    this.modals = modals;
    return this;
  }

  public InfoResponse putModalsItem(String key, Boolean modalsItem) {
    if (this.modals == null) {
      this.modals = new HashMap<String, Boolean>();
    }
    this.modals.put(key, modalsItem);
    return this;
  }

   /**
   * Get modals
   * @return modals
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, Boolean> getModals() {
    return modals;
  }


  public void setModals(Map<String, Boolean> modals) {
    this.modals = modals;
  }


  public InfoResponse navColor(String navColor) {
    
    this.navColor = navColor;
    return this;
  }

   /**
   * Get navColor
   * @return navColor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNavColor() {
    return navColor;
  }


  public void setNavColor(String navColor) {
    this.navColor = navColor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfoResponse infoResponse = (InfoResponse) o;
    return Objects.equals(this.columns, infoResponse.columns) &&
        Objects.equals(this.links, infoResponse.links) &&
        Objects.equals(this.managedNamespace, infoResponse.managedNamespace) &&
        Objects.equals(this.modals, infoResponse.modals) &&
        Objects.equals(this.navColor, infoResponse.navColor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columns, links, managedNamespace, modals, navColor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfoResponse {\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    managedNamespace: ").append(toIndentedString(managedNamespace)).append("\n");
    sb.append("    modals: ").append(toIndentedString(modals)).append("\n");
    sb.append("    navColor: ").append(toIndentedString(navColor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

