/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoArgoprojEventsV1alpha1EventSourceFilter;
import io.argoproj.workflow.models.IoArgoprojEventsV1alpha1WebhookContext;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IoArgoprojEventsV1alpha1WebhookEventSource
 */

public class IoArgoprojEventsV1alpha1WebhookEventSource {
  public static final String SERIALIZED_NAME_FILTER = "filter";
  @SerializedName(SERIALIZED_NAME_FILTER)
  private IoArgoprojEventsV1alpha1EventSourceFilter filter;

  public static final String SERIALIZED_NAME_WEBHOOK_CONTEXT = "webhookContext";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_CONTEXT)
  private IoArgoprojEventsV1alpha1WebhookContext webhookContext;


  public IoArgoprojEventsV1alpha1WebhookEventSource filter(IoArgoprojEventsV1alpha1EventSourceFilter filter) {
    
    this.filter = filter;
    return this;
  }

   /**
   * Get filter
   * @return filter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IoArgoprojEventsV1alpha1EventSourceFilter getFilter() {
    return filter;
  }


  public void setFilter(IoArgoprojEventsV1alpha1EventSourceFilter filter) {
    this.filter = filter;
  }


  public IoArgoprojEventsV1alpha1WebhookEventSource webhookContext(IoArgoprojEventsV1alpha1WebhookContext webhookContext) {
    
    this.webhookContext = webhookContext;
    return this;
  }

   /**
   * Get webhookContext
   * @return webhookContext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IoArgoprojEventsV1alpha1WebhookContext getWebhookContext() {
    return webhookContext;
  }


  public void setWebhookContext(IoArgoprojEventsV1alpha1WebhookContext webhookContext) {
    this.webhookContext = webhookContext;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojEventsV1alpha1WebhookEventSource ioArgoprojEventsV1alpha1WebhookEventSource = (IoArgoprojEventsV1alpha1WebhookEventSource) o;
    return Objects.equals(this.filter, ioArgoprojEventsV1alpha1WebhookEventSource.filter) &&
        Objects.equals(this.webhookContext, ioArgoprojEventsV1alpha1WebhookEventSource.webhookContext);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filter, webhookContext);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojEventsV1alpha1WebhookEventSource {\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    webhookContext: ").append(toIndentedString(webhookContext)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

