/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NodeFlag
 */

public class NodeFlag {
  public static final String SERIALIZED_NAME_HOOKED = "hooked";
  @SerializedName(SERIALIZED_NAME_HOOKED)
  private Boolean hooked;

  public static final String SERIALIZED_NAME_RETRIED = "retried";
  @SerializedName(SERIALIZED_NAME_RETRIED)
  private Boolean retried;


  public NodeFlag hooked(Boolean hooked) {
    
    this.hooked = hooked;
    return this;
  }

   /**
   * Hooked tracks whether or not this node was triggered by hook or onExit
   * @return hooked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Hooked tracks whether or not this node was triggered by hook or onExit")

  public Boolean getHooked() {
    return hooked;
  }


  public void setHooked(Boolean hooked) {
    this.hooked = hooked;
  }


  public NodeFlag retried(Boolean retried) {
    
    this.retried = retried;
    return this;
  }

   /**
   * Retried tracks whether or not this node was retried by retryStrategy
   * @return retried
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Retried tracks whether or not this node was retried by retryStrategy")

  public Boolean getRetried() {
    return retried;
  }


  public void setRetried(Boolean retried) {
    this.retried = retried;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeFlag nodeFlag = (NodeFlag) o;
    return Objects.equals(this.hooked, nodeFlag.hooked) &&
        Objects.equals(this.retried, nodeFlag.retried);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hooked, retried);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeFlag {\n");
    sb.append("    hooked: ").append(toIndentedString(hooked)).append("\n");
    sb.append("    retried: ").append(toIndentedString(retried)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

