/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.OSSLifecycleRule;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OSSArtifactRepository defines the controller configuration for an OSS artifact repository
 */
@ApiModel(description = "OSSArtifactRepository defines the controller configuration for an OSS artifact repository")

public class OSSArtifactRepository {
  public static final String SERIALIZED_NAME_ACCESS_KEY_SECRET = "accessKeySecret";
  @SerializedName(SERIALIZED_NAME_ACCESS_KEY_SECRET)
  private io.kubernetes.client.openapi.models.V1SecretKeySelector accessKeySecret;

  public static final String SERIALIZED_NAME_BUCKET = "bucket";
  @SerializedName(SERIALIZED_NAME_BUCKET)
  private String bucket;

  public static final String SERIALIZED_NAME_CREATE_BUCKET_IF_NOT_PRESENT = "createBucketIfNotPresent";
  @SerializedName(SERIALIZED_NAME_CREATE_BUCKET_IF_NOT_PRESENT)
  private Boolean createBucketIfNotPresent;

  public static final String SERIALIZED_NAME_ENDPOINT = "endpoint";
  @SerializedName(SERIALIZED_NAME_ENDPOINT)
  private String endpoint;

  public static final String SERIALIZED_NAME_KEY_FORMAT = "keyFormat";
  @SerializedName(SERIALIZED_NAME_KEY_FORMAT)
  private String keyFormat;

  public static final String SERIALIZED_NAME_LIFECYCLE_RULE = "lifecycleRule";
  @SerializedName(SERIALIZED_NAME_LIFECYCLE_RULE)
  private OSSLifecycleRule lifecycleRule;

  public static final String SERIALIZED_NAME_SECRET_KEY_SECRET = "secretKeySecret";
  @SerializedName(SERIALIZED_NAME_SECRET_KEY_SECRET)
  private io.kubernetes.client.openapi.models.V1SecretKeySelector secretKeySecret;

  public static final String SERIALIZED_NAME_SECURITY_TOKEN = "securityToken";
  @SerializedName(SERIALIZED_NAME_SECURITY_TOKEN)
  private String securityToken;

  public static final String SERIALIZED_NAME_USE_S_D_K_CREDS = "useSDKCreds";
  @SerializedName(SERIALIZED_NAME_USE_S_D_K_CREDS)
  private Boolean useSDKCreds;


  public OSSArtifactRepository accessKeySecret(io.kubernetes.client.openapi.models.V1SecretKeySelector accessKeySecret) {
    
    this.accessKeySecret = accessKeySecret;
    return this;
  }

   /**
   * Get accessKeySecret
   * @return accessKeySecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public io.kubernetes.client.openapi.models.V1SecretKeySelector getAccessKeySecret() {
    return accessKeySecret;
  }


  public void setAccessKeySecret(io.kubernetes.client.openapi.models.V1SecretKeySelector accessKeySecret) {
    this.accessKeySecret = accessKeySecret;
  }


  public OSSArtifactRepository bucket(String bucket) {
    
    this.bucket = bucket;
    return this;
  }

   /**
   * Bucket is the name of the bucket
   * @return bucket
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Bucket is the name of the bucket")

  public String getBucket() {
    return bucket;
  }


  public void setBucket(String bucket) {
    this.bucket = bucket;
  }


  public OSSArtifactRepository createBucketIfNotPresent(Boolean createBucketIfNotPresent) {
    
    this.createBucketIfNotPresent = createBucketIfNotPresent;
    return this;
  }

   /**
   * CreateBucketIfNotPresent tells the driver to attempt to create the OSS bucket for output artifacts, if it doesn&#39;t exist
   * @return createBucketIfNotPresent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "CreateBucketIfNotPresent tells the driver to attempt to create the OSS bucket for output artifacts, if it doesn't exist")

  public Boolean getCreateBucketIfNotPresent() {
    return createBucketIfNotPresent;
  }


  public void setCreateBucketIfNotPresent(Boolean createBucketIfNotPresent) {
    this.createBucketIfNotPresent = createBucketIfNotPresent;
  }


  public OSSArtifactRepository endpoint(String endpoint) {
    
    this.endpoint = endpoint;
    return this;
  }

   /**
   * Endpoint is the hostname of the bucket endpoint
   * @return endpoint
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Endpoint is the hostname of the bucket endpoint")

  public String getEndpoint() {
    return endpoint;
  }


  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }


  public OSSArtifactRepository keyFormat(String keyFormat) {
    
    this.keyFormat = keyFormat;
    return this;
  }

   /**
   * KeyFormat defines the format of how to store keys and can reference workflow variables.
   * @return keyFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "KeyFormat defines the format of how to store keys and can reference workflow variables.")

  public String getKeyFormat() {
    return keyFormat;
  }


  public void setKeyFormat(String keyFormat) {
    this.keyFormat = keyFormat;
  }


  public OSSArtifactRepository lifecycleRule(OSSLifecycleRule lifecycleRule) {
    
    this.lifecycleRule = lifecycleRule;
    return this;
  }

   /**
   * Get lifecycleRule
   * @return lifecycleRule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OSSLifecycleRule getLifecycleRule() {
    return lifecycleRule;
  }


  public void setLifecycleRule(OSSLifecycleRule lifecycleRule) {
    this.lifecycleRule = lifecycleRule;
  }


  public OSSArtifactRepository secretKeySecret(io.kubernetes.client.openapi.models.V1SecretKeySelector secretKeySecret) {
    
    this.secretKeySecret = secretKeySecret;
    return this;
  }

   /**
   * Get secretKeySecret
   * @return secretKeySecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public io.kubernetes.client.openapi.models.V1SecretKeySelector getSecretKeySecret() {
    return secretKeySecret;
  }


  public void setSecretKeySecret(io.kubernetes.client.openapi.models.V1SecretKeySelector secretKeySecret) {
    this.secretKeySecret = secretKeySecret;
  }


  public OSSArtifactRepository securityToken(String securityToken) {
    
    this.securityToken = securityToken;
    return this;
  }

   /**
   * SecurityToken is the user&#39;s temporary security token. For more details, check out: https://www.alibabacloud.com/help/doc-detail/100624.htm
   * @return securityToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "SecurityToken is the user's temporary security token. For more details, check out: https://www.alibabacloud.com/help/doc-detail/100624.htm")

  public String getSecurityToken() {
    return securityToken;
  }


  public void setSecurityToken(String securityToken) {
    this.securityToken = securityToken;
  }


  public OSSArtifactRepository useSDKCreds(Boolean useSDKCreds) {
    
    this.useSDKCreds = useSDKCreds;
    return this;
  }

   /**
   * UseSDKCreds tells the driver to figure out credentials based on sdk defaults.
   * @return useSDKCreds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UseSDKCreds tells the driver to figure out credentials based on sdk defaults.")

  public Boolean getUseSDKCreds() {
    return useSDKCreds;
  }


  public void setUseSDKCreds(Boolean useSDKCreds) {
    this.useSDKCreds = useSDKCreds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OSSArtifactRepository osSArtifactRepository = (OSSArtifactRepository) o;
    return Objects.equals(this.accessKeySecret, osSArtifactRepository.accessKeySecret) &&
        Objects.equals(this.bucket, osSArtifactRepository.bucket) &&
        Objects.equals(this.createBucketIfNotPresent, osSArtifactRepository.createBucketIfNotPresent) &&
        Objects.equals(this.endpoint, osSArtifactRepository.endpoint) &&
        Objects.equals(this.keyFormat, osSArtifactRepository.keyFormat) &&
        Objects.equals(this.lifecycleRule, osSArtifactRepository.lifecycleRule) &&
        Objects.equals(this.secretKeySecret, osSArtifactRepository.secretKeySecret) &&
        Objects.equals(this.securityToken, osSArtifactRepository.securityToken) &&
        Objects.equals(this.useSDKCreds, osSArtifactRepository.useSDKCreds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessKeySecret, bucket, createBucketIfNotPresent, endpoint, keyFormat, lifecycleRule, secretKeySecret, securityToken, useSDKCreds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OSSArtifactRepository {\n");
    sb.append("    accessKeySecret: ").append(toIndentedString(accessKeySecret)).append("\n");
    sb.append("    bucket: ").append(toIndentedString(bucket)).append("\n");
    sb.append("    createBucketIfNotPresent: ").append(toIndentedString(createBucketIfNotPresent)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    keyFormat: ").append(toIndentedString(keyFormat)).append("\n");
    sb.append("    lifecycleRule: ").append(toIndentedString(lifecycleRule)).append("\n");
    sb.append("    secretKeySecret: ").append(toIndentedString(secretKeySecret)).append("\n");
    sb.append("    securityToken: ").append(toIndentedString(securityToken)).append("\n");
    sb.append("    useSDKCreds: ").append(toIndentedString(useSDKCreds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

