/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.LabelSelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PodGC describes how to delete completed pods as they complete
 */
@ApiModel(description = "PodGC describes how to delete completed pods as they complete")

public class PodGC {
  public static final String SERIALIZED_NAME_DELETE_DELAY_DURATION = "deleteDelayDuration";
  @SerializedName(SERIALIZED_NAME_DELETE_DELAY_DURATION)
  private String deleteDelayDuration;

  public static final String SERIALIZED_NAME_LABEL_SELECTOR = "labelSelector";
  @SerializedName(SERIALIZED_NAME_LABEL_SELECTOR)
  private LabelSelector labelSelector;

  public static final String SERIALIZED_NAME_STRATEGY = "strategy";
  @SerializedName(SERIALIZED_NAME_STRATEGY)
  private String strategy;


  public PodGC deleteDelayDuration(String deleteDelayDuration) {
    
    this.deleteDelayDuration = deleteDelayDuration;
    return this;
  }

   /**
   * DeleteDelayDuration specifies the duration before pods in the GC queue get deleted.
   * @return deleteDelayDuration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "DeleteDelayDuration specifies the duration before pods in the GC queue get deleted.")

  public String getDeleteDelayDuration() {
    return deleteDelayDuration;
  }


  public void setDeleteDelayDuration(String deleteDelayDuration) {
    this.deleteDelayDuration = deleteDelayDuration;
  }


  public PodGC labelSelector(LabelSelector labelSelector) {
    
    this.labelSelector = labelSelector;
    return this;
  }

   /**
   * Get labelSelector
   * @return labelSelector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LabelSelector getLabelSelector() {
    return labelSelector;
  }


  public void setLabelSelector(LabelSelector labelSelector) {
    this.labelSelector = labelSelector;
  }


  public PodGC strategy(String strategy) {
    
    this.strategy = strategy;
    return this;
  }

   /**
   * Strategy is the strategy to use. One of \&quot;OnPodCompletion\&quot;, \&quot;OnPodSuccess\&quot;, \&quot;OnWorkflowCompletion\&quot;, \&quot;OnWorkflowSuccess\&quot;. If unset, does not delete Pods
   * @return strategy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Strategy is the strategy to use. One of \"OnPodCompletion\", \"OnPodSuccess\", \"OnWorkflowCompletion\", \"OnWorkflowSuccess\". If unset, does not delete Pods")

  public String getStrategy() {
    return strategy;
  }


  public void setStrategy(String strategy) {
    this.strategy = strategy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PodGC podGC = (PodGC) o;
    return Objects.equals(this.deleteDelayDuration, podGC.deleteDelayDuration) &&
        Objects.equals(this.labelSelector, podGC.labelSelector) &&
        Objects.equals(this.strategy, podGC.strategy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deleteDelayDuration, labelSelector, strategy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PodGC {\n");
    sb.append("    deleteDelayDuration: ").append(toIndentedString(deleteDelayDuration)).append("\n");
    sb.append("    labelSelector: ").append(toIndentedString(labelSelector)).append("\n");
    sb.append("    strategy: ").append(toIndentedString(strategy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

