/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.Metadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WorkflowLevelArtifactGC describes how to delete artifacts from completed Workflows - this spec is used on the Workflow level
 */
@ApiModel(description = "WorkflowLevelArtifactGC describes how to delete artifacts from completed Workflows - this spec is used on the Workflow level")

public class WorkflowLevelArtifactGC {
  public static final String SERIALIZED_NAME_FORCE_FINALIZER_REMOVAL = "forceFinalizerRemoval";
  @SerializedName(SERIALIZED_NAME_FORCE_FINALIZER_REMOVAL)
  private Boolean forceFinalizerRemoval;

  public static final String SERIALIZED_NAME_POD_METADATA = "podMetadata";
  @SerializedName(SERIALIZED_NAME_POD_METADATA)
  private Metadata podMetadata;

  public static final String SERIALIZED_NAME_POD_SPEC_PATCH = "podSpecPatch";
  @SerializedName(SERIALIZED_NAME_POD_SPEC_PATCH)
  private String podSpecPatch;

  public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_NAME = "serviceAccountName";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_NAME)
  private String serviceAccountName;

  public static final String SERIALIZED_NAME_STRATEGY = "strategy";
  @SerializedName(SERIALIZED_NAME_STRATEGY)
  private String strategy;


  public WorkflowLevelArtifactGC forceFinalizerRemoval(Boolean forceFinalizerRemoval) {
    
    this.forceFinalizerRemoval = forceFinalizerRemoval;
    return this;
  }

   /**
   * ForceFinalizerRemoval: if set to true, the finalizer will be removed in the case that Artifact GC fails
   * @return forceFinalizerRemoval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ForceFinalizerRemoval: if set to true, the finalizer will be removed in the case that Artifact GC fails")

  public Boolean getForceFinalizerRemoval() {
    return forceFinalizerRemoval;
  }


  public void setForceFinalizerRemoval(Boolean forceFinalizerRemoval) {
    this.forceFinalizerRemoval = forceFinalizerRemoval;
  }


  public WorkflowLevelArtifactGC podMetadata(Metadata podMetadata) {
    
    this.podMetadata = podMetadata;
    return this;
  }

   /**
   * Get podMetadata
   * @return podMetadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Metadata getPodMetadata() {
    return podMetadata;
  }


  public void setPodMetadata(Metadata podMetadata) {
    this.podMetadata = podMetadata;
  }


  public WorkflowLevelArtifactGC podSpecPatch(String podSpecPatch) {
    
    this.podSpecPatch = podSpecPatch;
    return this;
  }

   /**
   * PodSpecPatch holds strategic merge patch to apply against the artgc pod spec.
   * @return podSpecPatch
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PodSpecPatch holds strategic merge patch to apply against the artgc pod spec.")

  public String getPodSpecPatch() {
    return podSpecPatch;
  }


  public void setPodSpecPatch(String podSpecPatch) {
    this.podSpecPatch = podSpecPatch;
  }


  public WorkflowLevelArtifactGC serviceAccountName(String serviceAccountName) {
    
    this.serviceAccountName = serviceAccountName;
    return this;
  }

   /**
   * ServiceAccountName is an optional field for specifying the Service Account that should be assigned to the Pod doing the deletion
   * @return serviceAccountName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ServiceAccountName is an optional field for specifying the Service Account that should be assigned to the Pod doing the deletion")

  public String getServiceAccountName() {
    return serviceAccountName;
  }


  public void setServiceAccountName(String serviceAccountName) {
    this.serviceAccountName = serviceAccountName;
  }


  public WorkflowLevelArtifactGC strategy(String strategy) {
    
    this.strategy = strategy;
    return this;
  }

   /**
   * Strategy is the strategy to use.
   * @return strategy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Strategy is the strategy to use.")

  public String getStrategy() {
    return strategy;
  }


  public void setStrategy(String strategy) {
    this.strategy = strategy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowLevelArtifactGC workflowLevelArtifactGC = (WorkflowLevelArtifactGC) o;
    return Objects.equals(this.forceFinalizerRemoval, workflowLevelArtifactGC.forceFinalizerRemoval) &&
        Objects.equals(this.podMetadata, workflowLevelArtifactGC.podMetadata) &&
        Objects.equals(this.podSpecPatch, workflowLevelArtifactGC.podSpecPatch) &&
        Objects.equals(this.serviceAccountName, workflowLevelArtifactGC.serviceAccountName) &&
        Objects.equals(this.strategy, workflowLevelArtifactGC.strategy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(forceFinalizerRemoval, podMetadata, podSpecPatch, serviceAccountName, strategy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowLevelArtifactGC {\n");
    sb.append("    forceFinalizerRemoval: ").append(toIndentedString(forceFinalizerRemoval)).append("\n");
    sb.append("    podMetadata: ").append(toIndentedString(podMetadata)).append("\n");
    sb.append("    podSpecPatch: ").append(toIndentedString(podSpecPatch)).append("\n");
    sb.append("    serviceAccountName: ").append(toIndentedString(serviceAccountName)).append("\n");
    sb.append("    strategy: ").append(toIndentedString(strategy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

