FROM maven:3-eclipse-temurin-21 AS cache
COPY application /tmp/application
COPY frontend /tmp/frontend
COPY modules /tmp/modules
COPY pom.xml /tmp/pom.xml
WORKDIR /tmp
RUN mvn dependency:go-offline

FROM scratch
LABEL org.opencontainers.image.source=https://github.com/scc-digitalhub/digitalhub-core
COPY --from=cache /root/.m2 /root/.m2