CREATE TABLE IF NOT EXISTS runnable
(
    id      VARCHAR(255) NOT NULL PRIMARY KEY,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data    BINARY LARGE OBJECT,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
